services:
  mysql:
    image: mysql
    container_name: mysql_microservice
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservice
      MYSQL_USER: microservice
      MYSQL_PASSWORD: microservice
    ports:
      - "9999:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db