apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
stringData:
  MONGO_URI_VIDEO: mongodb://root:root@host.minikube.internal:27017/video?authSource=admin
  MONGO_URI_MP3: mongodb://root:root@host.minikube.internal:27017/mp3?authSource=admin
type: Opaque